name: code

on:
  push:

defaults:
  run:
    shell: bash

jobs:
  cancel-previous:
    name: Cancel redundant jobs
    runs-on: ubuntu-20.04
    timeout-minutes: 3
    if: github.ref != 'refs/heads/master'
    steps:
      - uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}

  yarn:
    strategy:
      matrix:
        command:
          - test
          - tsc --noEmit
      fail-fast: false

    name: ${{ matrix.command }}
    runs-on: ubuntu-20.04
    timeout-minutes: 2
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 16
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - run: yarn install

      - run: yarn ${{ matrix.command }}
